language: python
cache : pip
python:
    - 3.5
    - 3.6
    - 3.7


matrix:
    include:
    - name: "Python 3.6.5 on macOS 10.13"
          os: osx
          osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
          language: shell      
          before_install:
          - pip install -r requirements.txt
          script: coverage run --source=. setup.py test
          after_success: coveralls
    
    - name: "Python 3.7.3 on macOS 10.14"
          os: osx
          osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
          language: shell       
          before_install:
          - pip install -r requirements.txt
          script: coverage run --source=. setup.py test
          after_success: coveralls

      - name: "Python 3.7.4 on Windows"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell     
          before_install:
           - pip install -r requirements.txt
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
   - pip install -r requirements.txt

script:
    coverage run --source=. setup.py test

after_success:
    coveralls
